# Config file for automatic testing at travis-ci.org

language: python

python:
  - "2.7"
  - "3.4"

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install -r requirements.txt -r test_requirements.txt codecov coveralls

# command to run tests, e.g. python setup.py test
script:
  - coverage run --source esis setup.py test

after_success:
  - codecov
  - coveralls

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/fba129fb5d9dd058d5bf
